name: Build and Push Docker image

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

#      - name: Docker Login
#        run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASS}}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

  #    - name: Run docker build
  #      run: |
  #        docker build --tag sebkhedim/guestbook:1.0 guestbook/
  #        docker push sebkhedim/guestbook:1.0

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: sebkhedim/guestbook:1.0
          context: guestbook/

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
